const categoryIcons = [
    { icon_name: 'bowl', icon_type: 'entypo' },

    { icon_name: 'customerservice', icon_type: 'ant-design' },
    { icon_name: 'creditcard', icon_type: 'ant-design' },
    { icon_name: 'codesquareo', icon_type: 'ant-design' },
    { icon_name: 'book', icon_type: 'ant-design' },
    { icon_name: 'barschart', icon_type: 'ant-design' },
    { icon_name: 'bars', icon_type: 'ant-design' },
    { icon_name: 'clockcircle', icon_type: 'ant-design' },
    { icon_name: 'mail', icon_type: 'ant-design' },
    { icon_name: 'link', icon_type: 'ant-design' },
    { icon_name: 'home', icon_type: 'ant-design' },
    { icon_name: 'laptop', icon_type: 'ant-design' },
    { icon_name: 'star', icon_type: 'ant-design' },
    { icon_name: 'filter', icon_type: 'ant-design' },
    { icon_name: 'shoppingcart', icon_type: 'ant-design' },
    { icon_name: 'save', icon_type: 'ant-design' },
    { icon_name: 'user', icon_type: 'ant-design' },
    { icon_name: 'videocamera', icon_type: 'ant-design' },
    { icon_name: 'team', icon_type: 'ant-design' },
    { icon_name: 'sharealt', icon_type: 'ant-design' },
    { icon_name: 'setting', icon_type: 'ant-design' },
    { icon_name: 'picture', icon_type: 'ant-design' },
    { icon_name: 'tags', icon_type: 'ant-design' },
    { icon_name: 'cloud', icon_type: 'ant-design' },
    { icon_name: 'delete', icon_type: 'ant-design' },
    { icon_name: 'heart', icon_type: 'ant-design' },
    { icon_name: 'calculator', icon_type: 'ant-design' },

    { icon_name: 'archive', icon_type: 'entypo' },
    { icon_name: 'awareness-ribbon', icon_type: 'entypo' },
    { icon_name: 'baidu', icon_type: 'entypo' },
    { icon_name: 'basecamp', icon_type: 'entypo' },
    { icon_name: 'battery', icon_type: 'entypo' },
    { icon_name: 'bell', icon_type: 'entypo' },
    { icon_name: 'blackboard', icon_type: 'entypo' },
    { icon_name: 'block', icon_type: 'entypo' },
    { icon_name: 'book', icon_type: 'entypo' },
    { icon_name: 'bookmark', icon_type: 'entypo' },
    { icon_name: 'box', icon_type: 'entypo' },
    { icon_name: 'briefcase', icon_type: 'entypo' },
    { icon_name: 'brush', icon_type: 'entypo' },
    { icon_name: 'bucket', icon_type: 'entypo' },
    { icon_name: 'clapperboard', icon_type: 'entypo' },
    { icon_name: 'clipboard', icon_type: 'entypo' },
    { icon_name: 'colours', icon_type: 'entypo' },
]

export default categoryIcons